---
title: "Matlab Toolbox Heterogeneous Agents Dynamic Programming"
author: "Fan Wang"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Matlab Toolbox Heterogeneous Agents Dynamic Programming"
output:
  pdf_document:
    toc: true
    toc_depth: 5
    pandoc_args: '_output_kniti_pdf.yaml'
    includes:
      in_header: 'preamble_book.tex'
  html_document:
    pandoc_args: '_output_kniti_html.yaml'
always_allow_html: true
github-repo: fanwangecon/MEconTools
---

```{r global_options, include = FALSE}
source(".Rprofile")
```

# Preface {-}

`r text_top_count`

This is a work-in-progress Matlab package consisting of functions that facilitate Dynamic Programming and Related Tasks. Materials gathered from various [projects](https://fanwangecon.github.io/research) in which Matlab code is used. Some of the solutions/algorithms are research outputs developed for specific research [papers](https://fanwangecon.github.io/research), other algorithms and methods are commonly-used. Files are the [MEconTools](https://github.com/FanWangEcon/MEconTools) repository. Matlab files are linked below by section with livescript files. Tested with [Matlab](https://www.mathworks.com/products/matlab.html) 2019a [@matlab].

> Download and install the Matlab toolbox: [MEconTools.mltbx](https://github.com/FanWangEcon/MEconTools/blob/master/MEconTools.mltbx)

This bookdown file is a collection of mlx based vignettes for functions that are available from [MEconTools](https://github.com/FanWangEcon/MEconTools). Each Vignette file contains various examples for invoking each function. The goal of this repository is to make it easier to find/re-use codes produced for various projects.

From other repositories: For dynamic borrowing and savings problems, see [Dynamic Asset Repository](https://fanwangecon.github.io/CodeDynaAsset/); For code examples, see also [R Example Code](https://fanwangecon.github.io/R4Econ/), [Matlab Example Code](https://fanwangecon.github.io/M4Econ/), [Python Example Code](https://fanwangecon.github.io/Py4Econ/), and [Stata Example Code](https://fanwangecon.github.io/Stata4Econ/); For intro stat with R, see [Intro Statistics for Undergraduates](https://fanwangecon.github.io/Stat4Econ/), and intro Math with Matlab, see [Intro Mathematics for Economists](https://fanwangecon.github.io/Math4Econ/). See [here](https://github.com/FanWangEcon) for all of [Fan](https://fanwangecon.github.io/)'s public repositories.

The site is built using [Bookdown](https://bookdown.org/) [@R-bookdown].

Please contact [FanWangEcon](https://fanwangecon.github.io/) for issues or problems.

`r text_end_count`
